/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * API example
 * The example API description
 * OpenAPI spec version: 1.0
 */
import type { DogBreedsResponseMessage } from './dogBreedsResponseMessage';

export interface DogBreedsResponse {
  /** A map of dog breeds and their sub-breeds */
  message: DogBreedsResponseMessage;
  /** The status of the response */
  status: string;
}
