/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * API example
 * The example API description
 * OpenAPI spec version: 1.0
 */

/**
 * A map of dog breeds and their sub-breeds
 */
export type DogBreedsResponseMessage = { [key: string]: string[] };
