/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * API example
 * The example API description
 * OpenAPI spec version: 1.0
 */

export interface DogImage {
  /** Dog image */
  message: string;
  /** Response status */
  status: string;
}
