/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * API example
 * The example API description
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type { DogImage } from '.././model';

/**
 * @summary Get a random dog image
 */
export const dogsControllerGetImage = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DogImage>> => {
  return axios.get(`http://localhost:3000/dogs/image`, options);
};

export const getDogsControllerGetImageQueryKey = () => {
  return [`http://localhost:3000/dogs/image`] as const;
};

export const getDogsControllerGetImageQueryOptions = <
  TData = Awaited<ReturnType<typeof dogsControllerGetImage>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof dogsControllerGetImage>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDogsControllerGetImageQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dogsControllerGetImage>>
  > = ({ signal }) => dogsControllerGetImage({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dogsControllerGetImage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DogsControllerGetImageQueryResult = NonNullable<
  Awaited<ReturnType<typeof dogsControllerGetImage>>
>;
export type DogsControllerGetImageQueryError = AxiosError<unknown>;

/**
 * @summary Get a random dog image
 */

export function useDogsControllerGetImage<
  TData = Awaited<ReturnType<typeof dogsControllerGetImage>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof dogsControllerGetImage>>,
    TError,
    TData
  >;
  axios?: AxiosRequestConfig;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getDogsControllerGetImageQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
